name: Build Rust on Windows with full MinGW toolchain

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (GNU toolchain)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-x86_64-pc-windows-gnu
          override: true

      - name: Set up MSYS2 and install full MinGW toolchain
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            make
            cmake
            pkg-config
            clang
            llvm

      - name: Add MSYS2 MinGW bin to PATH
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Build Rust project
        run: cargo build --release
