name: windows-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-msvc:
    runs-on: windows-latest
    env:
      CC: cl.exe
      CXX: cl.exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: cargo test --verbose
  build-clang:
    runs-on: windows-latest
    env:
      CC: clang.exe
      CXX: clang++.exe
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: egor-tensin/setup-clang@v1
        with:
          platform: x64
      - run: cargo test --verbose
